# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        project:
            quality: 100
            filters:
                thumbnail:
                    size: [306, 250]
                    mode: outbound
        project_page:
            quality: 100
            filters:
                thumbnail:
                    size: [ 300, 500 ]
                    mode: outbound
